version: "3.7"

volumes: 
  postgres: ~
  postgres-test: ~

services:
  dev:
    depends_on: 
      - postgres
      - postgres-test
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/workspaces/sqlc-example
    working_dir: /workspaces/sqlc-example
    command: sleep infinity

  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=default
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=secret

  postgres-test:
    image: postgres:13-alpine
    volumes:
      - postgres-test:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=default
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=secret
