version: "3.7"

volumes: 
  postgres: ~

services:
  dev:
    depends_on: 
      - postgres
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ..:/workspaces/sqlc-example
    command: /bin/sh -c "while sleep 1000; do :; done"

  postgres:
    image: postgres:13
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=default
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=secret
