name: ci-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Start containers
        run: |
          docker-compose up -d
          docker-compose ps
      
      - name: Run tests
        shell: 'script -q -e -c "bash {0}"' # tty workaround
        run: docker-compose exec dev make test
